enableScripts: false
enableTelemetry: false
logFilters:
  - code: YN0007 # X must be built because it never has been before or the last one failed
    level: discard
  - code: YN0008 # X must be rebuilt because its dependency tree changed
    level: discard
  - code: YN0013 # X can't be found in the cache and will be fetched from the remote registry
    level: discard
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
yarnPath: .yarn/releases/yarn-3.4.1.cjs
