enableGlobalCache: false
enableTelemetry: false
logFilters:
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
packageExtensions:
  "@expo/cli@*":
    peerDependencies:
      expo-modules-autolinking: "*"
  babel-preset-expo@*:
    peerDependencies:
      "@babel/core": ^7.0.0-0
  expo-asset@*:
    peerDependencies:
      expo: "*"
  expo@*:
    peerDependencies:
      "@babel/core": ^7.0.0-0
yarnPath: .yarn/releases/yarn-4.2.2.cjs
