/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.2/userguide/java_library_plugin.html
 */

buildscript {
    repositories {
        google()
	jcenter()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:3.5.0")
    }
}
