require_relative '../../node_modules/react-native-test-app/test_app.rb'

workspace 'AsyncStorageExample.xcworkspace'

use_flipper! false
use_test_app! do |target|
  target.app do
    pod 'RNCAsyncStorage', :path => '../..'
    pod 'AsyncStorageExample', :path => '..'
  end
end
