require_relative '../../node_modules/react-native-test-app/macos/test_app.rb'

workspace 'AsyncStorageExample.xcworkspace'

options = {
  :fabric_enabled => false,
  :hermes_enabled => false,
  :turbomodule_enabled => false,
}

use_test_app! do |target|
  target.app do
    pod 'RNCAsyncStorage', :path => '../..'
    pod 'AsyncStorageExample', :path => '..'
  end

  target.ui_tests do
    pod 'AsyncStorageExample-UITests', :path => '.'
  end
end
